#!/bin/sh
# Container entrypoint implementing the canonical fleet durability pattern
# (docs/06-fleet-data-durability.md) for the router's two keys — its SSH
# host key and its proxy (bridge client) key. Unlike a game's image, there
# is no litestream here: the router holds no SQLite, so "durability" for it
# is only ever "back these two small key objects up to S3 and restore them
# on a fresh host" (bucket layout: keys/router/). The binary needs zero
# code changes for any of this — both keys already self-generate on first
# run if missing (see internal/server).
set -eu

HOST_KEY_PATH="${ARCADE_HOST_KEY_PATH:-/var/lib/arcade/ssh_host_key}"
PROXY_KEY_PATH="${ARCADE_PROXY_KEY_PATH:-/var/lib/arcade/proxy_key}"
# mc's own alias/bucket/key path, e.g. "s3/<bucket>/keys/router/ssh_host_key"
# — the alias's endpoint/credentials come from an MC_HOST_<alias> env var
# (mc's env-based alias mechanism), so this script has no bucket/region/
# credential logic of its own and works unchanged against real S3 or the
# MinIO used by local durability drills.
HOST_KEY_MC_PATH="${ARCADE_HOST_KEY_MC_PATH:-}"
PROXY_KEY_MC_PATH="${ARCADE_PROXY_KEY_MC_PATH:-}"

# Dev mode: no S3 key-backup wiring configured, skip straight to the app
# with a loud log line. Local dev and CI must never require AWS/MinIO
# credentials. In production the proxy key is typically a mounted
# read-only secret rather than something restored here — see below.
if [ -z "$HOST_KEY_MC_PATH" ] && [ -z "$PROXY_KEY_MC_PATH" ]; then
	echo "entrypoint: no key-backup path configured — running WITHOUT S3 key backup (dev mode)"
	exec /app/ssh-arcadelobby
fi

# Restores $key_path from $mc_path if the key isn't already there — a
# secret mounted read-only (production's proxy key) or a key generated by
# an earlier boot both count as "already there" and are left untouched.
#
# Writes to a temp path first: on a genuinely first-ever boot the bucket
# has no key yet and `mc cat` fails, but a bare `>"$key_path"` redirect
# still creates/truncates its target before mc even runs — leaving a
# 0-byte file that satisfies the app's own "does a key already exist"
# check and skips key generation entirely, crashing the server with "no
# key found". Only promote the temp file if mc actually produced non-empty
# content.
restore_key() {
	key_path="$1"
	mc_path="$2"
	[ -z "$mc_path" ] && return 0
	[ -f "$key_path" ] && return 0
	echo "entrypoint: restoring $key_path from $mc_path"
	if mc cat "$mc_path" >"$key_path.tmp" 2>/dev/null && [ -s "$key_path.tmp" ]; then
		mv "$key_path.tmp" "$key_path"
		chmod 600 "$key_path"
	else
		rm -f "$key_path.tmp"
		echo "entrypoint: no $key_path found in bucket yet — a new one will be generated and uploaded"
	fi
}

# The key may not exist locally yet (first boot ever: the app generates
# one when it starts) or may appear immediately (a mounted secret, or a
# key this same call just restored above). Upload it to the bucket as soon
# as it appears, in the background, so this instance seeds/refreshes the
# bucket without delaying startup.
backup_key_when_present() {
	key_path="$1"
	mc_path="$2"
	[ -z "$mc_path" ] && return 0
	i=0
	while [ "$i" -lt 30 ]; do
		if [ -f "$key_path" ]; then
			mc pipe "$mc_path" <"$key_path" 2>/dev/null \
				&& echo "entrypoint: $key_path uploaded to $mc_path"
			return 0
		fi
		i=$((i + 1))
		sleep 1
	done
}

restore_key "$HOST_KEY_PATH" "$HOST_KEY_MC_PATH"
restore_key "$PROXY_KEY_PATH" "$PROXY_KEY_MC_PATH"

(
	backup_key_when_present "$HOST_KEY_PATH" "$HOST_KEY_MC_PATH"
	backup_key_when_present "$PROXY_KEY_PATH" "$PROXY_KEY_MC_PATH"
) &

exec /app/ssh-arcadelobby
